version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dpo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dpo_db
    ports:
      - "9090:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
