services:
  postgres-production:
    container_name: postgres_production
    image: postgres
    restart: always
    env_file:
      - .production.env
    volumes:
      - postgres-production-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridge
    profiles:
      - production
      - production-storage

  postgres-development:
    container_name: postgres_development
    image: postgres
    restart: no
    env_file:
      - .development.env
    volumes:
      - postgres-development-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridge
    profiles:
      - development
      - development-storage

  backend-production:
    container_name: backend_production
    build:
      context: .
      args:
        - MODE=production
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - .:/app
    env_file:
      - .production.env
    environment:
      - MODE=production
    depends_on:
      - postgres-production
    networks:
      - bridge
    profiles:
      - production

  backend-development:
    container_name: backend_development
    build:
      context: .
      args:
        - MODE=development
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .development.env
    environment:
      - MODE=development
    depends_on:
      - postgres-development
    networks:
      - bridge
    profiles:
      - development

networks:
  bridge:
    driver: bridge

volumes:
  postgres-production-data:
  postgres-development-data:
  redis-development-data:
  redis-production-data:
